import Head from "next/head";
import { InternalLayout } from "@/src/layout/internalLayout";
import { useRouter } from "next/router";
import { updateReturnedItem } from "@/src/services/ReturnedService";
import "dayjs/locale/pt-br";
import ReturnedPage from "./returnedPage";

export async function getServerSideProps({ query }) {
  const id = query.id.toString();
  const baseUrl = process.env.API_URL;
  const googleKey = process.env.GOOGLE_MAP_KEY;
  const url = `${baseUrl}/returned?id=${id}`;
  const returnedItem = await fetch(url).then((response) => response.json());

  return {
    props: {
      returnedItem: returnedItem[0],
      googleKey,
    },
  };
}

function EditReturnedPage({ returnedItem, googleKey }) {
  const router = useRouter();

  function handleSave(data) {
    data._id = returnedItem._id;
    console.log(data);
    updateReturnedItem(data).then(() => {
      router.back();
    });
  }

  return (
    <>
      <Head>
        <title>Editanto devolução {returnedItem.titulo}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReturnedPage returnedItem={returnedItem} onSave={handleSave} googleKey={googleKey}></ReturnedPage>
    </>
  );
}
EditReturnedPage.PageLayout = InternalLayout;

export default EditReturnedPage;
