import { useState, useEffect } from "react";
import Head from "next/head";
import { InternalLayout } from "@/src/layout/internalLayout";
import {
  AppBar,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Grid,
  IconButton,
  InputBase,
  MenuItem,
  Paper,
  Toolbar,
} from "@mui/material";
import {
  deleteReturnedItem,
  getReturnedItems,
} from "@/src/services/ReturnedService";
import CardReturnedItem from "@/src/components/CardReturnedItem/CardReturnedItem";
import ActionMenu from "@/src/components/ActionMenu/ActionMenu";
import { Directions, Search } from "@mui/icons-material";

function ReturnedPage() {
  const [returnedList, setReturnedList] = useState([]);
  const [open, setOpen] = useState(false);
  const [selectedReturnedItemId, setSelectedReturnedItemId] = useState(null);

  const [searchValue, setSearchValue] = useState('');

  const handleSearchChange = (event) => {
    setSearchValue(event.target.value);
  };

  const handleSearchSubmit = () => {
    // aqui você pode utilizar o valor digitado pelo usuário
    console.log(searchValue);
  };

  const handleDeleteConfirmation = (returnedItemId) => {
    setSelectedReturnedItemId(returnedItemId);
    setOpen(true);
  };

  const handleClose = () => {
    setSelectedReturnedItemId(null);
    setOpen(false);
  };

  useEffect(() => {
    async function fetchReturned() {
      getReturnedItems().then((data) => {
        setReturnedList(data);
      });
    }

    fetchReturned();
  }, []);

  const handleEdit = (returnedItemId) => {
    alert(`Editando devolução ${returnedItemId}`);
  };

  const handleDelete = () => {
    deleteReturnedItem(selectedReturnedItemId).then(() => {
      setReturnedList(
        returnedList.filter(
          (returnedItem) => returnedItem._id !== selectedReturnedItemId
        )
      );
      handleClose();
    });
  };

  return (
    <>
      <Head>
        <title>Devolução</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper
        component="form"
        sx={{
          p: "2px 4px",
          display: "flex",
          alignItems: "center",
          marginBottom: 2,
        }}
      >
        <InputBase
          sx={{ ml: 1, flex: 1 }}
          placeholder="Pesquisar devolução"
          inputProps={{ "aria-label": "search google maps" }}
          value={searchValue}
        onChange={handleSearchChange}
        />
        <IconButton type="button" sx={{ p: "10px" }} aria-label="search">
          <Search />
        </IconButton>
        <Divider sx={{ height: 28, m: 0.5 }} orientation="vertical" />
        <input type="date" className="form-control" />
        <Chip color="primary" onClick={function () {}} size="small" sx={{width: 40}} variant="solid" />
        <Chip color="warning" onClick={function () {}} size="small" sx={{width: 40}} variant="solid" />
        <Chip color="success" onClick={function () {}} size="small" sx={{width: 40}} variant="solid" />
      </Paper>
      <Grid container spacing={2}>
        {returnedList.map((returnedItem) => (
          <CardReturnedItem
            key={returnedItem._id}
            returnedItem={returnedItem}
            action={
              <ActionMenu>
                <MenuItem onClick={() => handleEdit(returnedItem._id)}>
                  Editar
                </MenuItem>
                <MenuItem
                  onClick={() => handleDeleteConfirmation(returnedItem._id)}
                >
                  Excluir
                </MenuItem>
              </ActionMenu>
            }
          />
        ))}
      </Grid>
      <Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="responsive-dialog-title"
      >
        <DialogTitle id="responsive-dialog-title">
          {"Deletar devolução?"}
        </DialogTitle>
        <DialogContent>
          <DialogContentText>
            Tem certeza que deseja excluir este item?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button autoFocus onClick={handleClose}>
            Cancelar
          </Button>
          <Button onClick={handleDelete} autoFocus>
            Deletar
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
}
ReturnedPage.PageLayout = InternalLayout;

export default ReturnedPage;
