import { useState, useEffect } from "react";
import Head from "next/head";
import { InternalLayout } from "@/src/layout/internalLayout";
import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Grid,
  MenuItem,
} from "@mui/material";
import {
  deleteReturnedItem,
  getReturnedItems,
} from "@/src/services/ReturnedService";
import CardReturnedItem from "@/src/components/CardReturnedItem/CardReturnedItem";
import ActionMenu from "@/src/components/ActionMenu/ActionMenu";

function ReturnedPage() {
  const [returnedList, setReturnedList] = useState([]);
  const [open, setOpen] = useState(false);
  const [selectedReturnedItemId, setSelectedReturnedItemId] = useState(null);

  const handleDeleteConfirmation = (returnedItemId) => {
    setSelectedReturnedItemId(returnedItemId);
    setOpen(true);
  };

  const handleClose = () => {
    setSelectedReturnedItemId(null);
    setOpen(false);
  };

  useEffect(() => {
    async function fetchReturned() {
      getReturnedItems().then((data) => {
        setReturnedList(data);
      });
    }

    fetchReturned();
  }, []);

  const handleEdit = (returnedItemId) => {
    alert(`Editando devolução ${returnedItemId}`);
  };

  const handleDelete = () => {
    deleteReturnedItem(selectedReturnedItemId).then(() => {
      setReturnedList(
        returnedList.filter(
          (returnedItem) => returnedItem._id !== selectedReturnedItemId
        )
      );
      handleClose();
    });
  };

  return (
    <>
      <Head>
        <title>Devolução</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={2}>
        {returnedList.map((returnedItem) => (
          <CardReturnedItem
            key={returnedItem._id}
            returnedItem={returnedItem}
            action={
              <ActionMenu>
                <MenuItem onClick={() => handleEdit(returnedItem._id)}>
                  Editar
                </MenuItem>
                <MenuItem
                  onClick={() => handleDeleteConfirmation(returnedItem._id)}
                >
                  Excluir
                </MenuItem>
              </ActionMenu>
            }
          />
        ))}
      </Grid>
      <Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="responsive-dialog-title"
      >
        <DialogTitle id="responsive-dialog-title">
          {"Deletar devolução?"}
        </DialogTitle>
        <DialogContent>
          <DialogContentText>
            Tem certeza que deseja excluir este item?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button autoFocus onClick={handleClose}>
            Cancelar
          </Button>
          <Button onClick={handleDelete} autoFocus>
            Deletar
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
}
ReturnedPage.PageLayout = InternalLayout;

export default ReturnedPage;
