import { useState, useEffect } from "react";
import { formatDate } from "@/utils/date";
import Head from "next/head";
import devolucaoStyle from "@/styles/Devolucao.module.css";
import { InternalLayout } from "@/layout/internalLayout";

function DevolucoesPage() {
  const [devolucoes, setDevolucoes] = useState([]);

  useEffect(() => {
    const fetchDevolucoes = async () => {
      const res = await fetch("/api/devolucao");
      const data = await res.json();
      setDevolucoes(data);
    };

    fetchDevolucoes();
  }, []);

  return (
    <>
      <Head>
        <title>Devolucão</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={devolucaoStyle.container}>
        <h1>Devoluções</h1>
        <div className={devolucaoStyle.cardList}>
          {devolucoes.map((devolucao) => (
            <div className={devolucaoStyle.card} key={devolucao._id}>
              <h2 className={devolucaoStyle.local}>
                {devolucao.localDevolucao}
              </h2>
              <div className={devolucaoStyle.status}>{devolucao.status}</div>
              <p className={devolucaoStyle.data}>
                {formatDate(devolucao.dataLimite)}
              </p>
              <p className={devolucaoStyle.valor}>R$ {devolucao.valor}</p>
              <button className={devolucaoStyle.editar}>
                <i class="fas fa-pencil-alt"></i>
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

DevolucoesPage.PageLayout = InternalLayout;

export default DevolucoesPage;
