import * as React from "react";
import { useState, useEffect } from "react";
import Head from "next/head";
import { formatDate } from "@/utils/date";
import { InternalLayout } from "@/layout/internalLayout";
import {Card, CardHeader, CardContent, IconButton, Typography, Grid, Menu, MenuItem} from "@mui/material";
import MoreVertIcon from "@mui/icons-material/MoreVert";
import devolucaoStyle from "@/styles/Devolucao.module.css";

const options = [
  'Editar',
  'Excluir',
];

const ITEM_HEIGHT = 48;

function DevolucoesPage() {
  const [devolucoes, setDevolucoes] = useState([]);
  const [anchorEl, setAnchorEl] = useState(null);
  const open = Boolean(anchorEl);
  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };
  const handleClose = () => {
    setAnchorEl(null);
  };

  useEffect(() => {
    const fetchDevolucoes = async () => {
      const res = await fetch("/api/devolucao");
      const data = await res.json();
      setDevolucoes(data);
    };

    fetchDevolucoes();
  }, []);

  return (
    <>
      <Head>
        <title>Devolucão</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={2}>
        {devolucoes.map((devolucao) => (
          <Grid item xs={12} md={3} key={devolucao._id}>
            <Card>
              <CardHeader
                className={devolucaoStyle.MuiCardHeaderRoot}
                action={
                  <>
                  <IconButton
                    aria-label="more"
                    id="long-button"
                    aria-controls={open ? 'long-menu' : undefined}
                    aria-expanded={open ? 'true' : undefined}
                    aria-haspopup="true"
                    onClick={handleClick}
                  >
                    <MoreVertIcon />
                  </IconButton>
                  <Menu
                    id="long-menu"
                    MenuListProps={{
                      'aria-labelledby': 'long-button',
                    }}
                    anchorEl={anchorEl}
                    open={open}
                    onClose={handleClose}
                    PaperProps={{
                      style: {
                        maxHeight: ITEM_HEIGHT * 4.5,
                        width: '20ch',
                      },
                    }}
                  >
                    {options.map((option) => (
                      <MenuItem key={option} selected={option === 'Pyxis'} onClick={handleClose}>
                        {option}
                      </MenuItem>
                    ))}
                  </Menu>
                  </>
                }
                title={devolucao.localDevolucao}
                subheader={`R$ ${devolucao.valor}`}
              />
              <CardContent>
                <Typography sx={{ mb: 1.5 }} color="text.secondary">
                  {formatDate(devolucao.dataLimite)}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </>
  );
}

DevolucoesPage.PageLayout = InternalLayout;

export default DevolucoesPage;
