import Head from 'next/head'
import { Inter } from 'next/font/google'
import { InternalLayout } from '@/src/layout/internalLayout'
import { Button } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="contained">Contained</Button>
    </>
  )
}

Home.PageLayout = InternalLayout

export default Home;